CREATE TABLE `ride_hailing`.`ADMIN_DETAILS` 
(
     `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `EMAIL_ADDRESS` VARCHAR(255) UNIQUE NOT NULL,
     `PASSWORD` VARCHAR(255) NOT NULL,
     `FIRST_NAME` VARCHAR(32),
     `LAST_NAME` VARCHAR(32),
     `PHONE_NO` VARCHAR(12),
     `CNIC` CHAR(13),
     `CREDENTIALS` INT(1),
     PRIMARY KEY (`USER_ID`), 
     INDEX `USER_AUTH`(`EMAIL_ADDRESS`, `PASSWORD`)
) ENGINE = InnoDB;

INSERT INTO ADMIN_DETAILS
VALUES(0, 'saad@gmail.com', 'Password2109', 'Saad', 'Saqlain', '3137734043', '4213329578622', 1);

/*
     IS_ACTIVE: INACTIVE : 0, ACTIVE : 1
     RIDE_STATUS: NOT_ASSIGNED : 0, REQ_RECEIVED: 1, ACCEPTED: 2, CANCELLED: 3, COMPLETED: 4
     TODO: ADD FOREIGN KEY CONSTRAINT (USER_ID, ACTIVE_VEHICLE_ID) REFERENCES DRIVERS_VEHICLES(DRIVER_ID, VEHICLE_ID)
*/
CREATE TABLE `ride_hailing`.`DRIVER_DETAILS` 
(
     `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `USER_NAME` VARCHAR(32) NOT NULL,
     `FIRST_NAME` VARCHAR(32),
     `LAST_NAME` VARCHAR(32),
     `PHONE_NO` VARCHAR(12),
     `CNIC` CHAR(13),
     `LICENSE_NO` CHAR(6),
     `EMAIL_ADDRESS` VARCHAR(255) UNIQUE NOT NULL,
     `PASSWORD` VARCHAR(255) NOT NULL,
     `RATING` DECIMAL(5,4) NOT NULL DEFAULT 0,
     `NUM_RATINGS` INT(8) NOT NULL DEFAULT 0,
     `STATUS` INT(1) NOT NULL DEFAULT 0,
     `NUM_RIDES` INT(8) NOT NULL DEFAULT 0,
     `LATITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `LONGITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
     `IS_ACTIVE` BOOLEAN DEFAULT FALSE,
     `RIDE_STATUS` INT(1) DEFAULT 0,
     `RIDER_ID` INT(10) DEFAULT -1,
     `SOURCE_LAT` DECIMAL(9,6) NULL DEFAULT 0,
     `SOURCE_LONG` DECIMAL(9,6) NULL DEFAULT 0,
     `DEST_LAT` DECIMAL(9,6) NULL DEFAULT 0,
     `DEST_LONG` DECIMAL(9,6) NULL DEFAULT 0,
     `PAYMENT_MODE` INT(1),
     `RIDE_TYPE` INT(10) UNSIGNED NOT NULL DEFAULT 1,
     `SPLIT_FARE` BOOLEAN DEFAULT FALSE,
     `ACTIVE_VEHICLE_ID` INT(3) UNSIGNED DEFAULT 0,
     PRIMARY KEY (`USER_ID`),
     INDEX `USER_AUTH`(`EMAIL_ADDRESS`, `PASSWORD`)
) ENGINE = InnoDB;

CREATE TABLE `ride_hailing`.`VEHICLE_TYPES`
(
     `VEHICLE_TYPE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `MAKE` VARCHAR(16),
     `MODEL` VARCHAR(32),
     `YEAR` CHAR(4),
     `RIDE_TYPE_ID` INT(10) UNSIGNED NOT NULL,
     PRIMARY KEY (`VEHICLE_TYPE_ID`),
     FOREIGN KEY (`RIDE_TYPE_ID`) REFERENCES `RIDE_TYPES`(`TYPE_ID`),
     UNIQUE(`MAKE`, `MODEL`, `YEAR`)
) ENGINE = InnoDB;

INSERT INTO VEHICLE_TYPES VALUES(0, 'HONDA', 'CITY', '2013', 3),
(0, 'HONDA', 'INSIGHT', '2015', 2),
(0, 'HONDA', 'CITY', '2016', 3),
(0, 'HONDA', '120', '2018', 1),
(0, 'HONDA', 'CD70', '2012', 1),
(0, 'TOYOTA', 'COROLLA', '2017', 3),
(0, 'HONDA', 'ACCORD', '2013', 4),
(0, 'TOYOTA', 'CROWN', '2018', 4);

/*
* STATUS:
* 0 -> DEFAULT
* 1 -> SENT
* 2 -> REJECTED
* 3 -> ACCEPTED
*/
/* DRIVERS_VEHICLES DDL and inserts */
CREATE TABLE `ride_hailing`.`DRIVERS_VEHICLES`
(
     `DRIVER_ID` INT(10) UNSIGNED NOT NULL,
     `VEHICLE_ID` INT(3) UNSIGNED NOT NULL,
     `VEHICLE_TYPE_ID` INT(10) UNSIGNED NOT NULL,
     `NUMBER_PLATE` CHAR(8) NOT NULL,
     `STATUS` INT(1) DEFAULT 0,
     `COLOR` VARCHAR(32),
     PRIMARY KEY (`DRIVER_ID`, `VEHICLE_ID`),
     FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `VEHICLE_TYPES`(`VEHICLE_TYPE_ID`)
) ENGINE = InnoDB;

DELIMITER $$
CREATE OR REPLACE TRIGGER DV_ON_INSERT
     BEFORE INSERT ON DRIVERS_VEHICLES
FOR EACH ROW 
BEGIN
    SET NEW.VEHICLE_ID = (
       SELECT IFNULL(MAX(VEHICLE_ID), 0) + 1
       FROM DRIVERS_VEHICLES
       WHERE DRIVER_ID = NEW.DRIVER_ID);
END$$

/* --- --- END OF SECTION --- ---*/


/*
* STATUS:
* 0 -> DEFAULT
* 1 -> SENT
* 2 -> REJECTED
* 3 -> ACCEPTED
*/
CREATE TABLE `ride_hailing`.`VEHICLE_REGISTRATION_REQ`
(
     `DRIVER_ID` INT(10) UNSIGNED NOT NULL,
     `REGISTRATION_REQ_ID` INT(4) UNSIGNED AUTO_INCREMENT,
     `MAKE` VARCHAR(16),
     `MODEL` VARCHAR(32),
     `YEAR` CHAR(4),
     `NUMBER_PLATE` CHAR(8) NOT NULL,
     `COLOR` VARCHAR(32),
     `STATUS` INT(1) DEFAULT 0,
     PRIMARY KEY (`REGISTRATION_REQ_ID`),
     UNIQUE(`DRIVER_ID`, `NUMBER_PLATE`),
    FOREIGN KEY (`DRIVER_ID`) REFERENCES `DRIVER_DETAILS`(`USER_ID`)
) ENGINE = InnoDB; 


/* DROP EVERYTHING */
DROP TABLE `VEHICLE_REGISTRATION_REQ`;
DROP TABLE `DRIVERS_VEHICLES`;
DROP TABLE `VEHICLE_TYPES`;
DROP TABLE `DRIVER_DETAILS`;
DROP TABLE `ADMIN_DETAILS`;